### ISSUE TITLE
Feature suggestions -- see features in pypicolcd

### ISSUE THREAD

**Issue by Poikilos** [JamesTheAwesomeDude/pyPicoLCD#8]
Hello, I have massive notes on this device, and completely coded all by trial and error, but I wrote a couple different methods for writing to the device. It is named the same as yours except for all lowercase (pypicolcd; it is not a fork, it is something I wrote from scratch).
The way I did it seemed fairly hacky and inefficient since I couldn't find another way other than stepping through 8x32 blocks then writing stripes starting at the beginning of the block, but you could dig in and see if I did anything helpful: <https://github.com/poikilos/pypicolcd>. Here are some features I have that you may consider helpful:

* rect invalidation so refresh only draws changed areas (using offscreen buffer)
* my `push_text` method it is much faster than my other methods, since that only writes the strips that are necessary (does not write a whole block)
* I keep an offscreen buffer to allow for my `get_pixel_color` method to work and to avoid redundant writes
* I include an open-licensed font that is in chunks when viewed at full size but reduces well to a pixel font when at the height of a block/stripe on the 256x64 model
* I keep a pixel buffer (`_s_cache` as stripes formatted to the device's communication protocol, and `_f_cache` as PIL ImageFont) to avoid re-rendering fonts

Also, if you would, please let me know if my documentation has any missing information about how the device's communication protocol works (I'll see if I remember to check in again and read your code).

**Comment by James-E-A** [comment]
First, thank you for saying hi! I might never have noticed your work on this so far if you hadn't notified me with this Issue.

-----

I like all the work you've put into creating a "framebuffer" on the software-end, which is immediately useful from a programmer's standpoint: trading lower-level access to the PicoLCD's ridiculous API for a more traditional framebuffer that actually makes sense to interact with.

I hoped to create something like your project _eventually_, though my project is mainly trying to create the lowest-level API possible (trying to boil each of these "macros" down to the most atomic component actions the device has),. If I create a framebuffer, it'll be as an optional abstraction layer on top of the low-level API that I'm currently in the process of documenting.

-----

>Also, if you would, please let me know if my documentation has any missing information about how the device's communication protocol works 

To tie in to the previous bit, I notice that all your code (excepting backlight/HID) is so far leveraging your function `refresh_block`, which makes some assumptions about its usage (that the device's "cursor" will always want to be kept at a specific place, `cmd3` and `cmd4` are always batched together, etc.)

Most of what I've been doing so far is trying to figure out these "magic" commands:

* What do `cmd3` and `cmd2` _actually_ do? Are they atomic operations? (I think NOT! But I am having trouble reverse-engineering them...😓)
* Can the device's "internal cursor" be controlled without writing data?
* Are there any other useful commands hiding inside `OUT_REPORT_CMD`? (as mentioned in pt.1, I bet those "magic sequences" are actually strings of commands: like "move cursor, enable write mode, flush buffer", or something similar)
* How do the face-buttons work? (It seems to just be plain old HID: can we leverage existing libraries to support this while we're sending data to the device at the same time?) \*

> massive notes on this device, and completely coded all by trial and error

that's definitely annoying.  Sadly 😒 there's [nothing helpful from the manufacturer](https://github.com/JamesTheAwesomeDude/pyPicoLCD/issues/1#issuecomment-402861427) (except for the original source code itself); we've only got what we can get ourselves.

-----

\* re:HID: (I'm sure it's absolutely butchering the way the HID interface is "supposed" to be used, but it works...)

	from PicoLCD import PicoLcd;p=PicoLcd()
	BTNS=(None, "BACK", "HOME", "UNASSIGNED1", "UNASSIGNED2", "UP", "OK", "DOWN")
	BTNS[(p._read(),p._read())[0][1]] #You need the second read() call to "eat" the keyup event and clear the device's internal buffer

(I _suspect_ the UNASSIGNED1 and UNASSIGNED2 are something to do with its IR connector, J5 on the backpanel, though I have no way to even start verifying that)

**Comment by James-E-A** [comment]
so, **tl;dr @poikilos:** I unfortunately don't expect the documentation I'm currently generating will be very useful to you. 😞

A facsimile of `drv_pLG_update_img` is plenty enough power around which to build a framebuffer—you _already have_ have a fixed interface that lets you control all the pixels, which is really all you need!  
(I think. Unless you have something you're wondering about, in which case I'd love to share any of my thoughts so far on the interface, especially if you're wondering something specific.)

Whereas you probably(?) won't have as much use for breaking your perfectly suitable `refresh_block` function out into the actual atomic operations of the device's API, which is what I'm trying to reverse-engineer during this phase of my project.

**Comment by Poikilos** [comment]
Thanks for your response! I'll watch and star this and we'll see if we find any further optimizations. I got some of my protocol info from a linux driver mini-box provides that didn't work on my linux machine (I looked at the patched and unpatched versions of lcd4linux): http://resources.mini-box.com/online/picolcd/drivers/
